spring:
  application:
    name: SpringApplication
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${URL:jdbc:postgresql://localhost:5432/rentcar?autoreconnect=true}
    password: ${PASSWORD:root}
    username: ${USERMNAME:postgres}
  flyway:
    enabled: true
    validate-on-migrate: true
